[ranking_popular]
title = "다음 뉴스 ─ 랭킹 ─ 많이 본"
url = "https://news.daum.net/ranking/popular"
entrySelector = "//ul[@class='list_news2']/li[@data-tiara-layer='news_list']"
titleSelector = "//div[2]/strong/a"
linkSelector = "//div[2]/strong/a"
contentSelector = "//div[2]/strong/span[@class='info_news']"

[ranking_kkomkkom]
title = "다음 뉴스 ─ 랭킹 ─ 열독률 높은"
url = "https://news.daum.net/ranking/kkomkkom"
entrySelector = "//ul[@class='list_news2']/li[@data-tiara-layer='news_list']"
titleSelector = "//div[2]/strong/a"
linkSelector = "//div[2]/strong/a"
contentSelector = "//div[2]/strong/span[@class='info_news']"

[ranking_bestreply]
title = "다음 뉴스 ─ 랭킹 ─ 댓글 많은"
url = "https://news.daum.net/ranking/bestreply"
entrySelector = "//ul[@class='list_news2']/li[@data-tiara-layer='news_list']"
titleSelector = "//div[2]/strong/a"
linkSelector = "//div[2]/strong/a"
contentSelector = "//div[2]/strong/span[@class='info_news']"

[ranking_age]
title = "다음 뉴스 ─ 랭킹 ─ 연령별 ─ 20대이하 여성"
url = "https://news.daum.net/ranking/age"
entrySelector = "//html/body/div[2]/div[3]/div/div[1]/div[2]/div[1]/div[1]/ol/li"
titleSelector = "//a[@class='link_txt']"
linkSelector = "//a[@class='link_txt']"
contentSelector = "//span[@class='info_news']"
