[home]
title = "다음뉴스 ─ 홈"
url = "https://news.daum.net/"
entrySelector = "ul.list_newsissue li"
titleSelector = "strong.tit_g a.link_txt "
linkSelector = "strong.tit_g a.link_txt "
contentSelector = "span.txt_category"
waitUntil = "networkidle"

[society]
title = "다음뉴스 ─ 사회 ─ 메인뉴스"
url = "https://news.daum.net/society"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[politics]
title = "다음뉴스 ─ 정치 ─ 메인뉴스"
url = "https://news.daum.net/politics"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[economic]
title = "다음뉴스 ─ 경제 ─ 메인뉴스"
url = "https://news.daum.net/economic"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[foreign]
title = "다음뉴스 ─ 국제 ─ 메인뉴스"
url = "https://news.daum.net/foreign"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[culture]
title = "다음뉴스 ─ 문화 ─ 메인뉴스"
url = "https://news.daum.net/culture"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[digital]
title = "다음뉴스 ─ IT ─ 메인뉴스"
url = "https://news.daum.net/digital"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[photo]
title = "다음뉴스 ─ 포토"
url = "https://news.daum.net/photo"
entrySelector = "div.gallery_list.gallery_list2 ul.list_gallery li"
titleSelector = "strong.tit_thumb"
linkSelector = "a.link_cont"
contentSelector = "span.info_thumb a.link_txt"
imageSelector = "span.wrap_thumb img.thumb_g"
waitUntil = "networkidle"
