[home]
title = "다음뉴스 ─ 홈"
url = "https://news.daum.net/"
entrySelector = "ul.list_newsissue li"
titleSelector = "strong.tit_g a.link_txt "
linkSelector = "strong.tit_g a.link_txt "
contentSelector = "span.txt_category"
waitUntil = "networkidle"

[society]
title = "다음뉴스 ─ 사회 ─ 메인뉴스"
url = "https://news.daum.net/society"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[society_major]
title = "다음뉴스 ─ 사회 ─ 메이저"
url = "https://news.daum.net/society"
entrySelector = "div.box_g.box_news_major ul.list_newsmajor li"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "strong.tit_g span.info_cp"
waitUntil = "networkidle"

[politics]
title = "다음뉴스 ─ 정치 ─ 메인뉴스"
url = "https://news.daum.net/politics"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[politics_major]
title = "다음뉴스 ─ 정치 ─ 메이저"
url = "https://news.daum.net/politics"
entrySelector = "div.box_g.box_news_major ul.list_newsmajor li"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "strong.tit_g span.info_cp"
waitUntil = "networkidle"

[economic]
title = "다음뉴스 ─ 경제 ─ 메인뉴스"
url = "https://news.daum.net/economic"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[economic_major]
title = "다음뉴스 ─ 경제 ─ 메이저"
url = "https://news.daum.net/economic"
entrySelector = "div.box_g.box_news_major ul.list_newsmajor li"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "strong.tit_g span.info_cp"
waitUntil = "networkidle"

[foreign]
title = "다음뉴스 ─ 국제 ─ 메인뉴스"
url = "https://news.daum.net/foreign"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[foreign_major]
title = "다음뉴스 ─ 국제 ─ 메이저"
url = "https://news.daum.net/foreign"
entrySelector = "div.box_g.box_news_major ul.list_newsmajor li"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "strong.tit_g span.info_cp"
waitUntil = "networkidle"

[culture]
title = "다음뉴스 ─ 문화 ─ 메인뉴스"
url = "https://news.daum.net/culture"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[culture_major]
title = "다음뉴스 ─ 문화 ─ 메이저"
url = "https://news.daum.net/culture"
entrySelector = "div.box_g.box_news_major ul.list_newsmajor li"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "strong.tit_g span.info_cp"
waitUntil = "networkidle"

[digital]
title = "다음뉴스 ─ IT ─ 메인뉴스"
url = "https://news.daum.net/digital"
entrySelector = "ul.list_mainnews li"
titleSelector = "strong.tit_g a"
linkSelector = "strong.tit_g a"
contentSelector = "span.info_thumb span.txt_info"
waitUntil = "networkidle"

[digital_major]
title = "다음뉴스 ─ IT ─ 메이저"
url = "https://news.daum.net/digital"
entrySelector = "div.box_g.box_news_major ul.list_newsmajor li"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "strong.tit_g span.info_cp"
waitUntil = "networkidle"

[photo]
title = "다음뉴스 ─ 포토"
url = "https://news.daum.net/photo"
entrySelector = "div.gallery_list.gallery_list2 ul.list_gallery li"
titleSelector = "strong.tit_thumb"
linkSelector = "a.link_cont"
contentSelector = "span.info_thumb a.link_txt"
waitUntil = "networkidle"

[info_correct]
title = "다음뉴스 ─ 언론사 고침기사"
url = "https://news.daum.net/info/correct"
entrySelector = "ul.list_etc2.list_correction li:not(.item_border)"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "span.info_news span.info_txt"
dateSelector = "span.info_news span.info_time"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"

[info_revision]
title = "다음뉴스 ─ 언론중재법 피해구제보도"
url = "https://news.daum.net/info/revision"
entrySelector = "ul.list_etc2.list_correction li:not(.item_border)"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "span.info_news span.info_txt"
dateSelector = "span.info_news span.info_time"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"

[info_unfair]
title = "다음뉴스 ─ 불공정기사 모음"
url = "https://news.daum.net/info/unfair"
entrySelector = "ul.list_etc2.list_correction li:not(.item_border)"
titleSelector = "strong.tit_g a.link_txt"
linkSelector = "strong.tit_g a.link_txt"
contentSelector = "span.info_news span.info_txt"
dateSelector = "span.info_news span.info_time"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"
